project:
  type: website
  output-dir: docs

website:
  title: "Helen Grapow"
  description: "Helen Grapow is a PhD Candidate in Economics at Ghent University, Belgium."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: files/Grapow_CV.pdf
        text: CV
  page-footer:
    left: "(c) Helen Grapow"

format:
  html:
    theme:
      - cosmo
     
    toc: false
    fig-align: center



